### ISSUE TITLE
Not recognizing thieves' tools in inventory

### ISSUE THREAD

**Issue by Avitale34** [rinnocenti/innocenti-openlock#1]
Love this module super cool function! For some reason my rogue is only getting the strength option to open locks. I have "Thieves' Tools" equipped.
Edit: Also the lock is being removed even when that feature is not checked off.

**Comment by rinnocenti** [comment]
Make sure the name is exactly the same as the item. in the SRD is :

`Thieves’ Tools`

if you use a non-english language, copy and paste the exact name in the module settings.

Also if you use force to "open" the lock, it is always removed no matter what you select in the settings, after all it has been broken.

**Comment by Avitale34** [comment]
Copy and pasting the name worked but I am using the SRD "Thieves' Tools" so not sure why it didn't work by default! Oh well thank you! Script is great!

**Comment by rinnocenti** [comment]
in the case of thives'tool you need to be aware because the character of the apostrophe is different:
`'`

`’ `
