### ISSUE TITLE
How do you make Locks more reusable?

### ISSUE THREAD

**Issue by samcrudge** [rinnocenti/innocenti-openlock#11]
If i edit the location of one lock it edits them all (of the same lock feature). I'm new to Foundry and if I've done something wrong I'm sorry but is this by design?

**Comment by rinnocenti** [comment]
if you duplicate the actor with iten in there and edit the item, he will change them all.  this way is not ideal.
the ideal is to have the item (lock) in the items tab and add it only in the actor of the token.
so the added item is unique.  and will not be changed at the source.
