### ISSUE TITLE
Traps not activating / detonating

### ISSUE THREAD

**Issue by Tatonker** [rinnocenti/innocenti-openlock#13]
Hi,

I believe I have everything set up correctly, I can get the checks to work, the boxes to pop up for Break lock, pick lock and unset trap, but, I'm unable to get the trap to actually detonate / trigger on a failed attempt. I've added the following into the 'details' sheet of the "lock' feat:

1 Action
Melee Attack
2d6 piercing damage

When I run the 'Find Trap' macro I can see that it is registering the trap, but its not firing. Can you please advise the correct settings to use to create a workable trap effect eg. 2d6 Piercing?

Thanks,

Tatonker

**Comment by rinnocenti** [comment]
Sorry for late, But I'll bug fixed that now!
