### ISSUE TITLE
Foundry v0.8.5 module has wrong download link, Furnace Discontinued

### ISSUE THREAD

**Issue by FaeyUmbrea** [rinnocenti/innocenti-openlock#15]
The Manifest file specifies the archive of the main branch, when it should be https://github.com/rinnocenti/innocenti-openlock/archive/refs/heads/v.0.8.5.zip

**Comment by rinnocenti** [comment]
I'll fix it

**Comment by FaeyUmbrea** [comment]
I have an amendment here, the Furnace module no longer exists:
https://github.com/League-of-Foundry-Developers/fvtt-module-furnace
It has been incorporated into the core and split up into smaller projects. As such it should be removed from the dependency list and suceeded accordingly.

**Comment by rinnocenti** [comment]
Update for 8.6 is was corrected from dependencies
