### ISSUE TITLE
no open lock is shown

### ISSUE THREAD

**Issue by ThoGri75** [rinnocenti/innocenti-openlock#16]
hello,

after creating a new item (feature) and open it, no open lock menu is shown.

foundry 0.8.6
dnd 1.3.3
all needed modules are installed and enabled

**Comment by rinnocenti** [comment]
I cannot reproduce the error.
Any error in Console?
do you try in a new world?

**Comment by ThoGri75** [comment]
yes I generate a new world, because on an old world ts was not working to

[log.txt](https://github.com/rinnocenti/innocenti-openlock/files/6580146/log.txt)

**Comment by ThoGri75** [comment]
error?
foundry.js:3199 Template systems/dnd5e/templates/items//feat.html is referencing the entity attribute of provided sheet rendering data which is deprecated in favor of the data attribute. Support will be removed in 0.9.0

**Comment by ThoGri75** [comment]
[foundry.donnerstein.de-1622575905767.log](https://github.com/rinnocenti/innocenti-openlock/files/6580175/foundry.donnerstein.de-1622575905767.log)

**Comment by rinnocenti** [comment]
it's probably a module update error. remove the module and do a new installation.

**Comment by rinnocenti** [comment]
I'll create a new instance mor safe.. wait after new update please

**Comment by ThoGri75** [comment]
after the update it works, thanks
