### ISSUE TITLE
No "Open Lock" in feature 

### ISSUE THREAD

**Issue by SATANYASHA2017** [rinnocenti/innocenti-openlock#17]
I have non any window for setuping my lock.
I created a feature with name Lock , but...there is no section Open Lock((
![image](https://user-images.githubusercontent.com/86288543/123069874-0d835c80-d435-11eb-87f6-f7ab8d9e6219.png)
![image](https://user-images.githubusercontent.com/86288543/123069903-1411d400-d435-11eb-9dbb-323da108673c.png)
Особенность - means feature (russian localization)
![image](https://user-images.githubusercontent.com/86288543/123069989-2db31b80-d435-11eb-9cf5-d195c988beec.png)
![image](https://user-images.githubusercontent.com/86288543/123070011-34da2980-d435-11eb-977a-379b584b441f.png)

**Comment by rinnocenti** [comment]
I'll fixed in new Update
