### ISSUE TITLE
Cannot fill the Open Lock tab

### ISSUE THREAD

**Issue by tcatrain** [rinnocenti/innocenti-openlock#18]
Hello !

I have been trying to use this module with version 0.8.8 of Foundry VTT. I don't know if it is related to this specific version, but I cannot fill any field of the open lock tab.
The tab is re-rendered on the onchange event, and all modifications are lost.
After I commented the render call in the onchange event listener, I managed to have a lock working properly, but I am still facing a second issue : the trap isn't triggering when a check fails.

Do you have any insights of this issue ?
Kind regards.

**Comment by tcatrain** [comment]
I am not sure yet how it works (I started using Foundry VTT a few days ago...) but it seems to me that the tab is rendered, but the value from the input in not binded to the openlock attribute of the tab (see screenshot). I hope it helps...

![attribute not binded](https://user-images.githubusercontent.com/516852/125096482-7aede900-e0d5-11eb-9ff0-c749f550313e.png)

**Comment by rinnocenti** [comment]
this is usually because you are editing an actor inside a token that already has a padlock item in it.

Foundry has some issues when editing an item within a scene actor.

Ideally, you should configure the item OUTSIDE the actor's sheet.
