### ISSUE TITLE
Not working in 0.8.8?

### ISSUE THREAD

**Issue by RavenknightDM** [rinnocenti/innocenti-openlock#20]
Hiya, thanks for the mod. I can't get it working with the latest version of Foundry though. The chests stay closed even if the characters succeed on their rolls. I wonder if there are any updates coming? It's a good mod. I would hate to see it abandoned.

**Comment by RavenknightDM** [comment]
HA! New release just a couple of hours after I wrote the above. Thanks man. :D

**Comment by rinnocenti** [comment]
I'll chande same things and update this module soon

**Comment by Wolfemllts** [comment]
Version 0.8.9 is out right now. Still appears to be issues with this mod in newer versions of Foundry.

1.) Successful rolls to unlock a chest give an error when it attempts to open the chest afterwards (it almost appears like it is trying to open the chest before it finishes updating the character access rights to the chest as after the error the character is able to click on the chest again and it opens fine.)
2.) With the option on to remove the Lock once it has been picked/broken, it does not work. Tested picking/breaking lock and after the rights to open it update and the chest it opened the Lock remains in the inventory of the chest.

Mod still appears to work on door just fine in 0.8.9 and I love that functionality.

**Comment by rinnocenti** [comment]
I'll remake de module soon
