### ISSUE TITLE
Trap is always found.

### ISSUE THREAD

**Issue by Lanomir** [rinnocenti/innocenti-openlock#22]
When an actor searches the door or chest, the trap's presence is always detected regardless of the find traps DC.  Am I doing something wrong?

I love this Foundry module and I'm excited to use it.  Thank you for your hard work!

**Comment by rinnocenti** [comment]
can you explain to me how you are doing? or record a video with the steps you are doing?
remembering if the player's passive perception overcomes the DC he always finds.

**Comment by rinnocenti** [comment]
![image](https://user-images.githubusercontent.com/3178127/142333778-28e3f284-9909-4a48-b270-8ef49af9ef20.png)
here is working

**Comment by Lanomir** [comment]
Hello!  Here's a screen print of what I have set up.  I set the DC to 100,
but it still shows that the trap was found.  Any advice that you can give
is greatly appreciated.

[image: image.png]

**Comment by rinnocenti** [comment]
the image was not sent.
but it is probably passive awareness that is being overcome.

**Comment by Lanomir** [comment]
I increased the passive awareness DC, but it's still auto-finding the
trap.  Sorry for the questions.  I've attached a .PNG file showing what I'm
seeing.

**Comment by rinnocenti** [comment]
when you reply via e-mail the images are not sent and i can't understand your problem as i can't reproduce it
