### ISSUE TITLE
Reset the sate of the lock for a token

### ISSUE THREAD

**Issue by Rubengam3r** [rinnocenti/innocenti-openlock#23]
Currently when a token goes up to a door and does the OpenLock action if they are able to get the lock open the same token can come back and the door just opens. Is there a way to reset the lock on the door so that if the same token comes back but the door is locked it will not just open automatically?

**Comment by Rubengam3r** [comment]
It seems that the module either stores the token or a flag gets set stating that this token has already used the OpenLock and has opened the door. I am just looking for a way to reset that so that I can come back with that token during a campaign and not have the door bypass the checks.

**Comment by rinnocenti** [comment]
technically, there are no flags in this module, it recognizes from permission.
if the player has the door's token permission, he accesses without testing, if he doesn't do the tests.
As the idea is that once a player has overcome the challenge at the door, it doesn't make much sense for him to have to overcome it several times.
but it is still possible, just remove the player's permission from the token that will be asked for a new test.

**Comment by Rubengam3r** [comment]
Alright so if I understand right. Just take the player's permission of ownership off of the token for the door and then it should ask for a new test.  And if memory serves me right it should show that permission on the lootsheet. I will give that a go thanks.

**Comment by Rubengam3r** [comment]
Awsome! That worked really well. Thanks for help!
