### ISSUE TITLE
Seems to not work

### ISSUE THREAD

**Issue by Akallabeth13666** [rinnocenti/innocenti-openlock#24]
Hi, 

I cannot get this module to work properly.
All seems functional except the fact that after successful check I cannot open the chest.
Seems like permissions are not changed automatically.

![obraz_2022-06-15_111041264](https://user-images.githubusercontent.com/95130435/173790118-a8e4033f-841a-423f-b1f4-e059c33ebe99.png)

**Comment by rinnocenti** [comment]
I'll check this soon

**Comment by TheRarita** [comment]
Is this module still maintained?

**Comment by rinnocenti** [comment]
Yes.
New version in v10 will comming

**Comment by rprejean** [comment]
Foundry V9
DnD5e 1.6.3
IOD 0.4.6

I'm having a similar issue to this. All works well checks are rolled; however, there is no dialog about pass/fail and the lock doesn't change and chest/doors do not open automatical.

Images show trying to pick a chest lock that the lock is set at 1 for automatic success.

![image](https://user-images.githubusercontent.com/4765489/191841573-8067941c-45dc-47d5-9175-6b16bd579c4f.png)
![image](https://user-images.githubusercontent.com/4765489/191841621-85a4bb97-c5c6-4b32-ac09-7ddc53685d3f.png)
![image](https://user-images.githubusercontent.com/4765489/191841762-26c9862e-17ca-447d-a0bf-89c47efcf83b.png)

**Comment by rinnocenti** [comment]
press f12
any arror on console?

**Comment by rprejean** [comment]
No errors on the console that I can see. I logged in under a player account and get this.
![image](https://user-images.githubusercontent.com/4765489/191861278-e8a7e9ea-60f6-4e76-bbe3-cfc4e3ef68af.png)

**Comment by rprejean** [comment]
I take that back, on the GM account, I get a Uncaught (In promise) error.
![image](https://user-images.githubusercontent.com/4765489/191861549-b2ab568e-f30e-4c0c-99a1-015d8b3dd9a8.png)

**Comment by rprejean** [comment]
Player account, the console doesn't change and stays blank when activating either the Find Trap or Open Chest macro.

**Comment by rprejean** [comment]
I fixed the issue with the Player permissions. I changed the player configuration permissions to allow the Use Script Macro. But the action still does not complete the cycle of unlocking and opening a chest.

**Comment by rprejean** [comment]
Any word on why this module isn't working?

**Comment by rprejean** [comment]
On a whim, I turned of BetterRolls... That made this module start working!
