### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by rprejean** [rinnocenti/innocenti-openlock#26]
I had high hopes but it seems broken. 
- Foundry V9
- Build 280
- DnD5e 1.6.3
- Active modules 93
- IOL versions tested 0.7.9 from the manifest and 0.4.6 from the foundry load.

I loaded Innocenti Open Lock and all required dependencies. Attempted to create an item of the type Feature as instructed. The "Open Lock" tab is missing. I would assume this may be a conflict with one of my other mods. However, considering they are all working as expected, I'm not going to disable them to get this one mod working. 

The second issue that I ran into was the macros. They are nowhere to be found in the compendium. 

The third issue encountered when clicking update in the Foundry Virtual Tabletop - Configuration Setup, the mod downgrades to 0.4.6.

**Comment by rinnocenti** [comment]
open lock will only appear if the character has the item thieves' tools.
Depending on how you have created the items the apostrophe of the item name is different although graphically it looks the same.

I advise you to go to the configuration tab, and give ctrl+c cntrl+V in the name

**Comment by rprejean** [comment]
Thank you. That got things moving. I have another issue that is related to Akalabeth. I posted there for continuity.
