### ISSUE TITLE
No "Open Lock" tab in the lock item menu

### ISSUE THREAD

**Issue by CamIsBadAtNames** [rinnocenti/innocenti-openlock#3]
I created the lock as a feature in the items tab, however when I opened it, I am not seeing the tab for "Open Lock". 

![Innocenti Openlock](https://user-images.githubusercontent.com/67007113/99910687-5fa4a980-2cbd-11eb-8f45-516e89a41df1.png)

**Comment by rinnocenti** [comment]
can you see if there is an error pressing f12?
probably some other module is preventing startup

**Comment by CamIsBadAtNames** [comment]
I created a new game with only this module + the 3 required modules to run it and I am still having the same issue. Here is a screenshot of the error on the f12 menu. 

![Innocenti Openlock2](https://user-images.githubusercontent.com/67007113/99915406-7ead3680-2cd1-11eb-812b-86c05142561c.png)

**Comment by rinnocenti** [comment]
delete the module and install it again.
You must have caught a wrong commit during the update.

**Comment by rinnocenti** [comment]
anyway I will do an update so that if someone else has caught this commit I can update.

**Comment by CamIsBadAtNames** [comment]
It's working perfectly now, thank you so much!
