### ISSUE TITLE
Sometimes after loading cannot open Actors or Items

### ISSUE THREAD

**Issue by UnoriginalDM** [rinnocenti/innocenti-openlock#8]
Sometimes when loading Foundry with this mod active with its dependencies I get errors trying to open Actors and Items. Without the mod, the issue never occurs even if I still have the dependencies active.
![image](https://user-images.githubusercontent.com/77896718/109229453-ee2b3a00-7788-11eb-8ea6-520d934500b2.png)

If I am able to access Actors and Items. I can no longer adjust the size of the window of Features. Spells, Weapons, Backpacks, etc still allow me to adjust the size of the window.
![image](https://user-images.githubusercontent.com/77896718/109229857-89bcaa80-7789-11eb-9945-6e264ed6d594.png)

**Comment by rinnocenti** [comment]
What system version and module?
You have teste and a world without any other modules?

**Comment by UnoriginalDM** [comment]
Foundry Core Version: 0.7.9
DnD 5e Version: 1.2.4
Innocenti OpenLock Version: 0.3.3
Midi QoL Version: 0.3.72
Furnace Version: 2.6.0
LootSheetNPC Version: 2.5.1

I tested it in a fresh world with no other mods other than the dependencies. 
The issue with not opening actors and items has happened less since I posted this.
What I have also noticed that if I open a Feature and reset the sheet by simply clicking "Save Sheet Configuration". I can scale the Feature again until I re-log back in.
![image](https://user-images.githubusercontent.com/77896718/109381230-9979e300-789e-11eb-8435-ca5a035e1e28.png)

**Comment by rinnocenti** [comment]
the first error is probably OS / Browser
The second is a bug in the update, I will resolve it in a next update.
It may be that the update improves the incidence of the first.

**Comment by UnoriginalDM** [comment]
Thank you appreciate it.

**Comment by rinnocenti** [comment]
Fix in v 0.3.4
